### ISSUE TITLE
Panels change setting to always visible and duplicate when activating widget

### ISSUE THREAD

**Issue by rodrigoesborges** [psifidotos/workflow-project#67] opened 2013-02-08 23:16 UTC
![bug-workflow-plasmoid](https://f.cloud.github.com/assets/3339104/141331/ea88a114-7244-11e2-9d80-70bc81a6989f.png)

All my panels are duplicated , changed to 'always visible' setting and can't open settings for them, after restarting X with plasmoid activated on one of the panels.

It happens with 1 / 2 screens , one or multiple panels before set to "always hide", KDE 4.8.2 , KDE 4.9.5 and KDE 4.10 on Suse 12.2 32 bits with NVIDIA proprietary driver

**Comment by psifidotos** [comment] 2013-02-09 10:23
Ohhhh, that's big....
are you using the master version?
If yes, then give me a few days to clean up a bit the code and remove some hacks which may create that conflict...

If not, then I can try to debug it together with you...

When the hacks are removed I will send a notice here...

P.S. If you have installed the plasmoid from source it would be good to make a clean uninstall before testing new versions (that is because after version 0.2.2 the structure of the plasmoid has changed a lot)

**Comment by psifidotos** [comment] 2013-02-09 10:39
can you test with development branch ? (I have removed a feature that could create this issue)

**Comment by psifidotos** [comment] 2013-02-09 18:03
I have just tested for "Always hide" for panel for version in development branch and the issue you are describing is not triggerred... Please make a test to check if this problem remains for you.... I use OpenSuse 12.2, KDE 4.9, plasmoid version: development branch

**Comment by rodrigoesborges** [comment] 2013-02-09 19:44
I will try the development branch then. I was using before the master
version.

Finally, I offer my help at any way I can, since the plasmoid seems really
nice. I will try to help with translations to spanish/portuguese.

Congratulations for the work so far!

2013/2/9 Michail Vourlakos notifications@github.com

**Comment by rodrigoesborges** [comment] 2013-02-09 20:29
I confirm that installing from development branch solved the issue. 

It's a pity only that now when putting the plasmoid on a panel there is no way to show windows previews anymore.

But the problem stated has been solved! Thanks for the help!

**Comment by psifidotos** [comment] 2013-02-09 21:08
Óôéò 09/02/2013 10:29 ìì, ï/ç recognitium Ýãñáøå:

**Comment by bmihaila** [comment] 2013-02-10 17:58
Hi

I can confirm that window previews are not working on my system either. Unless by preview you mean the icons. The screenshot shows what I get with window previews enabled:
![screenshot](https://f.cloud.github.com/assets/2682197/143501/4f9d162c-73ab-11e2-9a24-9580f9c4563c.png)

But maybe I am using something wrong. In the previews calibration GUI I also do not see anything.

**Comment by psifidotos** [comment] 2013-02-10 18:12
Hmmmm, that is strange ...
Do me a favor and follow these steps:

1) set the plasmoid with no previews
2) In a console:
  kquitapp plasma-desktop
  plasma-desktop &
3) wait for everything to load - especially for the various popups - wait to be hidden
4) click to see the plasmoid from the panel
5) enable previews from inside the plasmoid
6) click in a preview as in your previous photo in order to make sure that the preview
has been loaded (not all previews are loaded by default in kwin)

lets see....

**Comment by psifidotos** [comment] 2013-02-10 18:14
beautiful photo BTW .... :) :+1:

**Comment by bmihaila** [comment] 2013-02-10 19:06
Ok, I have done the steps you wanted and no change. Unfortunately there are no error messages in the console either.

But I found another bug. In the previews UI the window state button has only 3 states, the "everywhere" state is missing and when pressing the "single" state button in the preview area you get the js type error:
`file:///usr/share/kde4/apps/plasma/plasmoids/workflow/contents/ui/delegates/ui-elements/TaskPreviewButtons.qml:68: TypeError: Result of expression 'taskDeleg2.dTypes' [undefined] is not an object.`

**Comment by bmihaila** [comment] 2013-02-10 19:07
> beautiful photo BTW .... :)

That's your work ;)

**Comment by psifidotos** [comment] 2013-02-10 23:38
Well, in development branch I have added a feature that can be of handy...
in calibration dialog in the up right corner there is a refresh button.
This is used to go through all open windows in order to test window previews.
(The plasmoid's popup is one of them). Use it and tell if you had any success and in what number?
the last one or another?

**Comment by psifidotos** [comment] 2013-02-10 23:40
BTW, in the calibration dialog the preview can be dragged... Imagine a movie in vlc in dragging... :)

**Comment by bmihaila** [comment] 2013-02-11 00:37
Hi again.

Sorry, no success. The preview area in the calibration dialog is empty black as before and the refresh button does not change anything. The preview itself just shows the icon like in my last screenshot. As it has always been like this from the first time I used the plasmoid it might be something related to my system?

**Comment by psifidotos** [comment] 2013-02-11 11:44
> plasmoid it might be something related to my system? 
> You mean that windows previews in the panel have never worked in your 
> system?

Ok, some questions:
Distro version?
KDE version?

in the calibration dialog next to refresh button, it should be a label
that goes downwards every time you click the button,
does that exist?

have window previews been enabled from the window effects?
do you see window previews from the default task manager?

**Comment by psifidotos** [comment] 2013-02-11 11:50
recognitium can you help us with the window previews to debug it?

P.S. for translation you can use the transifex site:
https://www.transifex.com/projects/p/WorkFlow_Project/

We may need to make a meeting with anyone interested in helping out to solve the window previews issue,
in project's irc channel that is: #workflow-project   in freenode servers.

**Comment by bmihaila** [comment] 2013-02-11 12:30
> You mean that windows previews in the panel have never worked in your system?

Yes.

> have window previews been enabled from the window effects? 

Not sure but I do see window previews in the alt+tab switcher though.

> do you see window previews from the default task manager?

Nope.

Ok, now I have been playing around with the KDE settings and managed to make it work.

I had to enable the "Taskbar Thumbnails" in the desktop effects. Now the previews appear. Everything seems to work :).

> in the calibration dialog next to refresh button, it should be a label that goes downwards every time you click the button, does that exist?

Yep, and after enabling the effect and being able to see the previews I can answer your earlier question:

> Use it and tell if you had any success and in what number? the last one or another?

It is the last number.

**Comment by bmihaila** [comment] 2013-02-11 12:32
Another issues though with the previews. When hovering over the preview in the previews window the preview itself gets bigger and the close and state buttons are pushed out of the window, thus it is very difficult to click them. See screenshot below with the buttons only partially visible on the right:

![screenshot](https://f.cloud.github.com/assets/2682197/144973/06bae5f0-7447-11e2-9994-5f3e0f35c4b0.png)

**Comment by rodrigoesborges** [comment] 2013-02-11 12:54
After fetching latest development files I checked that it solves my issue with windows preview and does not reproduce latest bmihaila bug. And actually, the calibration dialog improved: it almost got instantly the right settings (before I had to use like X 13 an Y 14, now only needs X 3-4 and Y 1-3)

I entered the channel, and will hang around there during the day just in case I can help with something

**Comment by psifidotos** [comment] 2013-02-11 15:19
@bmihaila, these are good news.... for the new issue this occurs when there is one window only in the window, right?

@recognitium, these are also good news. The new X.Y values is just the offset based on the current plasma theme, if the plasma theme changes then these values must be changed also

P.S. try dragging the window preview in the calibration dialog... I love this feature... :) , it opens the way to drag window previews in the main window also instead of just showing the window icon...

**Comment by bmihaila** [comment] 2013-02-11 17:33
> for the new issue this occurs when there is one window only in the window, right?

Yep, only then. Otherwise things work nice ;)
You could maybe still mention somewhere in the documentation that one needs the KDE effects enabled. Would have never come to my mind and you might get users to re-report this bug.

**Comment by psifidotos** [comment] 2013-02-11 19:03
> You could maybe still mention somewhere in the documentation that one
> needs the KDE effects enabled. Would have never come to my mind and you
> might get users to re-report this bug.
> 
> Problem is that there is no documentation and how to's in order to use the
> application and I can not maintain a wiki. If someone wants to help in this
> I am all open ears. To write two - three wiki pages or FAQ and we can
> upload it in various places (project page etc..)

**Comment by psifidotos** [comment] 2013-02-11 20:10
fixed in development branch

**Closed as completed by psifidotos** 2013-02-11 20:10 UTC

**Comment by bmihaila** [comment] 2013-02-14 00:51
> Problem is that there is no documentation and how to's in order to use the application and I can not maintain a wiki. If someone wants to help in this I am all open ears. To write two - three wiki pages or FAQ and we can upload it in various places (project page etc..)

Ok, I can try to set something up here on github with their wiki language. Won't be special but enough as a FAQ. I think it would be good to have some things explained (e.g. wallpapers, previews, search, reordering, delete workspaces ... most of the issues here that got either fixed or are in discussion). Will try to get to writing something during the weekend hopefully. But I think you guys should have a look over it as you know better what the issues are and also correct mistakes.

**Comment by psifidotos** [comment] 2013-02-14 07:26
No problem, I will definetely check it out...
