### ISSUE TITLE
Unattaching the plasmoid is not needed

### ISSUE THREAD

**Issue by mdaffin** [psifidotos/workflow-project#33] opened 2012-11-23 02:00 UTC
Is there any need to be able to unattach the plasmoid from its base? At the moment it makes the plasmoid feel buggy and I see no actual usecase for this.

It also adds a unneeded frame and title bar to the plasmoid which if removed would make it look more like all the other plasmoids and fit into the system better.

**Comment by psifidotos** [comment] 2012-11-23 18:24
I agree but I dont know how to disable it. The problem is that I dont know if my implementation is correct actually. To give you an idea the plasmoid is a hybrid one (C++ and QML) and it must be able to act as a PopUpApplet when it is placed in the panel.

The current implementation around this is in the workflow.cpp file in functions init()  and  initExtenderItem(). There must  be a better way to implement it but I dont know how (this is my first project in KDE, so I am still learning actually :) ). 

The current implementation must be relevant with other bugs also, for example the plasmoid does not remember the popup window size when logging in or out from KDE.

I would love to have a plasmoid example that:
1) is a hybrid one (C++ and QML)
2) it must be able to act as a PopUpApplet when it is placed in the panel.

**Comment by mdaffin** [comment] 2012-11-23 20:19
I have already started looking at the code and have been able to remove the ExtenderItem from the code, which is what is causing it. However the QDeclrativeWidget is not being placed in the layout properly. I haven't have much time to look at it though.

I will upload my changes to a new branch in my fork when I have some time to tidy them up (currently just quick hacks to see if it will work).

**Comment by mdaffin** [comment] 2012-11-23 21:16
You might want to look at the [homerun](https://projects.kde.org/projects/playground/base/homerun/repository) widget, it is QML based with some small c++ parts to it.

It has a nice way of starting the popup so it is basically full screen which I think will work nicely with this widget as well.

**Comment by psifidotos** [comment] 2012-12-04 17:04
It is fixed in master, I found a solution to remove extender and use the default behavior for popupapplet

**Closed as completed by psifidotos** 2012-12-04 17:04 UTC
